### ISSUE TITLE
How to run the end to end tests?

### ISSUE THREAD

**Issue by johnhooks** [erikyo/typescript-wp-block#3]
Does the `wp-env` need to be running during `npm run test`?

**Comment by johnhooks** [comment]
no that's not the issue, I figured it out, to run the tests the following is required:
```sh
$ npm run wp-env:start # I didn't do this the first time I tried and the e2e tests failed
$ npm run test
```

**Comment by erikyo** [comment]
Yes, but in theory it should not be this package that installs wp, but it must be installed globally.

https://developer.wordpress.org/block-editor/reference-guides/packages/packages-env/

**Comment by johnhooks** [comment]
Though it is a valid option to have it as a dependency. It still only installs a single docker instance.

https://developer.wordpress.org/block-editor/reference-guides/packages/packages-env/#installation-as-a-local-package
