### ISSUE TITLE
Including all the @types/wordpress__* packages

### ISSUE THREAD

**Issue by johnhooks** [erikyo/typescript-wp-block#6]
Should all the `@types/wordpress__*` packages be included as `devDependencies`? I haven't quite figured out what the canonical solution is.

**Comment by erikyo** [comment]
that's a good question but, afaik, due how the gutenberg repo is structured the types are exported separately and the way to use them is this. by the way i could be wrong or something could have changed in the meantime...

**Comment by johnhooks** [comment]
I don't know either. We'll leave it as it is, and keep learning
